[package]
name = "suitescript_generator"
version = "0.1.0"
authors = ["Donovan Dicks <donovan.dicks@logmein.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
