// TODO: Add list of accepted SuiteScript API modules 

pub const TYPES: [&str; 7] = [
    "mapreduce",
    "userevent",
    "scheduled",
    "client",
    "suitelet",
    "portlet",
    "restlet",
];

pub const API: [&str; 4] = [
    "2.1",
    "2",
    "2.x",
    "2.0",
];

pub const MODULES: [&str; 48] = [
    "action",
    "auth",
    "cache",
    "certificatecontrol",
    "commerce",
    "compress",
    "config",
    "crypto",
    "crypto/certificate",
    "currency",
    "currentrecord",
    "dataset",
    "email",
    "encode",
    "error",
    "file",
    "format",
    "format/i18n",
    "http",
    "https",
    "https/clientcertificate",
    "keycontrol",
    "log",
    "piremoval",
    "plugin",
    "portlet",
    "query",
    "record",
    "recordcontext",
    "redirect",
    "render",
    "runtime",
    "search",
    "sftp",
    "sso",
    "suiteappinfo",
    "task",
    "task/accounting/recognition",
    "transaction",
    "translation",
    "ui/dialog",
    "ui/message",
    "ui/serverwidget",
    "url",
    "util",
    "workbook",
    "workflow",
    "xml",
];
